#include <string>
#include <vector>
#include <iostream>
#include <algorithm>
#include <iomanip>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <sstream>
#include <numeric>
#include <chrono>
#include <stdexcept>
#include <list>
#include <deque>

using std::accumulate;
using std::string;
using std::vector;
using std::cout;
using std::cin;
using std::endl;
using std::sort;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::fixed;
using std::ifstream;
using std::cerr;
using std::ofstream;
using std::stringstream;
using std::runtime_error;
using std::exception;
using std::pair;
using std::deque;
using std::list;

